# Generated by Django 5.2.7 on 2025-10-18 13:49

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="audio",
            field=models.FileField(
                upload_to="audio/", validators=[api.validators.validate_audio_file]
            ),
        ),
    ]
